pub const FRUITS: [&'static str; 309] = [
    "Apple",
    "Apricot",
    "Avocado",
    "Abiu",
    "Acai",
    "Acerola",
    "Ackee",
    "Arhat",
    "American Mayapple",
    "African Cherry Orange",
    "Amazon grape",
    "Araza",
    "Alligator apple",
    "Ambarella",
    "African Cucumber",
    "African Medlar",
    "African Moringa",
    "Agave Plant",
    "Aizen Fruit",
    "American Black Elderberry",
    "American Chestnut",
    "American Hazelnut Shrub",
    "American Red Raspberry",
    "Aprium",
    "Atemoya",
    "Atherton Raspberry",
    "Banana",
    "Berry",
    "Bayberry",
    "Blueberry",
    "Blackberry",
    "Boysenberry",
    "Bearberry",
    "Bilberry",
    "Barberry",
    "Buffaloberry",
    "Black cherry",
    "Beach plum",
    "Black raspberry",
    "Black apple",
    "Blue tongue",
    "Bolwarra",
    "Burdekin plum",
    "Bramble",
    "Broadleaf Bramble",
    "Black mulberry",
    "Blood orange",
    "Babaco",
    "Bael",
    "Barbadine",
    "Barbados cherry",
    "Betel nut",
    "Bilimbi",
    "Bitter gourd",
    "Black sapote",
    "Bottle gourd",
    "Brazil nut",
    "Breadfruit",
    "Burmese grape",
    "Blackcurrant",
    "Bignay",
    "Beechnut",
    "Bacuri Fruit",
    "Balsam Apple",
    "Batuan Fruit",
    "Blood Lime",
    "Brazilian Guava",
    "Brush cherry",
    "Cantaloupe",
    "Chokeberry",
    "Cranberry",
    "Cloudberry",
    "Crowberry",
    "Conkerberry",
    "Calabash",
    "Calamansi",
    "Calamondins",
    "Canistel",
    "Cape Gooseberry",
    "Capuli Cherry",
    "Carob Fruit",
    "Cashew Apple",
    "Cedar Bay Cherry",
    "Cempedak",
    "Ceylon Gooseberry",
    "Charichuelo Fruit",
    "Chayote Fruit",
    "Cherimoya Fruit",
    "cherry Fruit",
    "Chokecherry",
    "Citrofortunella",
    "Clementines",
    "Cluster Fig",
    "Coco Plum",
    "Common Apple Berry",
    "Cornelian Cherry",
    "Cucumber",
    "Cupuacu",
    "Damson",
    "Date plum",
    "Davidson's plum",
    "Dead Man's Fingers",
    "Dekopon",
    "Desert fig",
    "Desert lime",
    "Dodder laurel",
    "Double Coconut",
    "Dragon Fruit",
    "Duku fruit",
    "Durian",
    "Eastern Hawthorn",
    "Elephant apple",
    "Emu Apple",
    "Emu berry",
    "Fairchild tangerine",
    "False mastic",
    "Feijoa",
    "Fibrous Satinash",
    "Finger Lime",
    "Florida strangler fig",
    "Forest strawberries",
    "Gac Fruit",
    "Galia melon",
    "Gambooge",
    "Genip",
    "Giant Granadilla",
    "Golden apple",
    "Goumi Fruit",
    "Governor�s Plum",
    "Granadilla",
    "Grapefruit",
    "Grapes",
    "Grapple",
    "Greengage",
    "Ground Plum",
    "Grumichama",
    "Guanabana",
    "Guarana",
    "Guavaberry",
    "Hackberry",
    "Hardy-kiwi",
    "Hawthorn",
    "Honeydew",
    "Honeysuckle",
    "Horned melon",
    "Huckleberry",
    "Huito",
    "Ice Cream Bean",
    "Ilama",
    "Illawarra Plum",
    "Imbe fruit",
    "Indian almond",
    "Indian Fig",
    "Indian Gooseberry",
    "Indian jujube",
    "Indian Prune",
    "Jabotacaba",
    "Jackfruit",
    "Jambul fruit",
    "Japanese Persimmon",
    "Jatoba fruit",
    "Jelly Palm",
    "Jocote",
    "Jostaberry",
    "Jujube",
    "Junglesop",
    "Juniper berry",
    "Kabosu Fruit",
    "Kaffir lime",
    "Kahikatea",
    "Kakadu plum",
    "Kapok",
    "Karkalla",
    "Karonda",
    "Kei apple",
    "Kepel",
    "Keule",
    "Kiwi",
    "Korlan",
    "Kumquat",
    "Kundong",
    "Kutjera",
    "Kwai Muk",
    "Lablab",
    "Lady apple",
    "Lakoocha",
    "Langsat",
    "Lapsi",
    "Lardizabala",
    "Lemato",
    "Lemon aspen",
    "Lemons",
    "Leucaena",
    "Lillypilly",
    "Limeberry",
    "Limequat",
    "Lingonberry",
    "Loganberry",
    "Loquat",
    "Lucuma",
    "Lychee",
    "Macadamia",
    "Madrono",
    "Malay Apple",
    "Mamey Sapote",
    "Mammee Apple",
    "Mamoncillo",
    "Mandarin",
    "Mangaba",
    "Mangosteen",
    "Manila Tamarind",
    "Manoao",
    "Ma-praang",
    "Maqui",
    "Marang",
    "Marionberry",
    "Marula",
    "Mayan Nut",
    "Mayapple",
    "Maypop",
    "Melinjo",
    "MelonPear",
    "Midyim",
    "Miracle fruit",
    "Mock Strawberry",
    "Monstera Delicisiosa",
    "Mora de Castilla",
    "Morinda",
    "Mountain pepper",
    "Mountain Soursop",
    "Muscadine",
    "Naartjie",
    "Nageia",
    "Nance",
    "Naranjilla",
    "Nectacotum",
    "Nectarines",
    "Neem",
    "Nere",
    "Nonda plum",
    "Nungu",
    "Nutmeg",
    "Oil Palm",
    "Olallieberry",
    "Olive",
    "Orangelo",
    "Oranges",
    "Oregon grape",
    "Oroblanco",
    "Ortanique",
    "Otaheite gooseberry",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Peach palm",
    "Peanut",
    "Pears",
    "Pecan",
    "Pequi",
    "Persian lime",
    "Persimmon",
    "Peumo",
    "Phalsa",
    "Physalis Fruit",
    "Pigeon pea",
    "Pigeon plum",
    "Pigface",
    "Pili Nut",
    "Pine apple",
    "Pineberry",
    "Pink-flowered Native Raspberry",
    "Plum",
    "Plumcot",
    "Pluot",
    "Pomato",
    "Pomegranate",
    "Pulasan",
    "Pummelo",
    "Rambutan",
    "Rangpur",
    "Red Mombin",
    "Riberry",
    "Rollinia",
    "Rose Apple",
    "Safou",
    "Salak",
    "Santol",
    "Sapodilla",
    "Soncoya",
    "Star Apple",
    "Star Fruit",
    "Strawberry guava",
    "Sugar Apple",
    "Sweet Orange",
    "Sweet Pepper",
    "Tamarind",
    "Tangelo",
    "Tangor",
    "Tayberry",
    "Tomato",
    "Ugli",
    "Vanilla",
    "Velvet apple",
    "Walnut",
    "Watermelon",
    "Wax jambu",
    "White sapote",
    "Youngberry",
    "Yuzu",
];
